version: "3.8"

services: 
  app:
    image: get_user_info
    network_mode: host
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    environment:
      - DB_IP=postgres
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on: 
      - postgres
  
  postgres:
    image: postgres:latest
    network_mode: host
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./initsql:/docker-entrypoint-initdb.d